In [32]:
#Import library numpy, pandas dan scikit-learn
import numpy as np
import pandas as pd
from sklearn import tree

In [33]:
#Membaca Dataset dari File ke Pandas dataFrame
irisDataset = pd.read_csv('canceled_test.csv', delimiter=';', header=0)

In [34]:
irisDataset.head()

ORDER_NO                      DATE  LINE  CUSTOMER_NO      ITEM  NC_ORDER  \
0    528703  Tuesday, January 3, 2017     1      1857566  10135139         1   
1    528705  Tuesday, January 3, 2017     1      1857566  10135140         1   
2    528706  Tuesday, January 3, 2017     2      1857566  10135138         1   
3    528707  Tuesday, January 3, 2017     1      1857566  10135132         1   
4    528708  Tuesday, January 3, 2017     1      1857566  10135359         1   

   NC_SHIP  
0        1  
1        1  
2        1  
3        1  
4        1

In [35]:
#Mengubah kelas (kolom "Species") dari String ke Unique-Integer
irisDataset["DATE"] = pd.factorize(irisDataset.DATE)[0]

In [36]:
irisDataset.head()

ORDER_NO  DATE  LINE  CUSTOMER_NO      ITEM  NC_ORDER  NC_SHIP
0    528703     0     1      1857566  10135139         1        1
1    528705     0     1      1857566  10135140         1        1
2    528706     0     2      1857566  10135138         1        1
3    528707     0     1      1857566  10135132         1        1
4    528708     0     1      1857566  10135359         1        1

In [37]:
print(irisDataset)

      ORDER_NO  DATE  LINE  CUSTOMER_NO      ITEM  NC_ORDER  NC_SHIP
0       528703     0     1      1857566  10135139         1        1
1       528705     0     1      1857566  10135140         1        1
2       528706     0     2      1857566  10135138         1        1
3       528707     0     1      1857566  10135132         1        1
4       528708     0     1      1857566  10135359         1        1
...        ...   ...   ...          ...       ...       ...      ...
3657    543485    48     8      2203715  10135140         3        3
3658    543488    48     6      2203449   1040468         2        2
3659    543488    48     7      2203449   1040466         1        1
3660    543491    48     5      2203449  10135358        21       21
3661    543491    48     9      2203449  10135363         6        6

[3662 rows x 7 columns]


In [38]:
#Menghapus kolom "Id"
irisDataset = irisDataset.drop(labels="ORDER_NO", axis=1)

In [39]:
print(irisDataset)

      DATE  LINE  CUSTOMER_NO      ITEM  NC_ORDER  NC_SHIP
0        0     1      1857566  10135139         1        1
1        0     1      1857566  10135140         1        1
2        0     2      1857566  10135138         1        1
3        0     1      1857566  10135132         1        1
4        0     1      1857566  10135359         1        1
...    ...   ...          ...       ...       ...      ...
3657    48     8      2203715  10135140         3        3
3658    48     6      2203449   1040468         2        2
3659    48     7      2203449   1040466         1        1
3660    48     5      2203449  10135358        21       21
3661    48     9      2203449  10135363         6        6

[3662 rows x 6 columns]


In [41]:
#Mengubah dataFrame ke array Numpy
irisDataset = irisDataset.to_numpy()

In [42]:
print(irisDataset)

[[       0        1  1857566 10135139        1        1]
 [       0        1  1857566 10135140        1        1]
 [       0        2  1857566 10135138        1        1]
 ...
 [      48        7  2203449  1040466        1        1]
 [      48        5  2203449 10135358       21       21]
 [      48        9  2203449 10135363        6        6]]


In [43]:
#Membagi Dataset => 80 baris data untuk training dan 20 baris data untuk testing
dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]), 
                              axis=0)
dataTesting = np.concatenate((irisDataset[40:50, :], irisDataset[90:100, :]), 
                             axis=0)

In [44]:
print(dataTesting)
len(dataTesting)

[[       2        3  1254694  1029070        1        1]
 [       2        4  1254694 10138006        1        1]
 [       2        5  1254694  1029071        1        1]
 [       2        6  1254694 10138004        1        1]
 [       2        7  1254694  1033341        1        1]
 [       2        8  1254694  1040827        1        1]
 [       2        9  1254694 10106111        1        1]
 [       2       10  1254694 10136162        1        1]
 [       2       11  1254694 10105916        1        1]
 [       2       12  1254694 10137990        1        1]
 [       4        3  1509644  1041108        1        1]
 [       4        4  1509644  1040991        1        1]
 [       4        5  1509644  1040992        1        1]
 [       4        6  1509644  1038324        1        1]
 [       4        7  1509644  1038323        1        1]
 [       4        8  1509644  1040726        1        1]
 [       4        9  1509644  1029071        1        1]
 [       4       10  1509644   

20

In [45]:
#Memecah Dataset ke Input dan Label
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]

In [46]:
#Mendefinisikan Decision Tree Classifier
model = tree.DecisionTreeClassifier()

In [47]:
#Mentraining Model
model = model.fit(inputTraining, labelTraining)

In [48]:
#Memprediksi Input Data Testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1]
Hasil Prediksi :  [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  5 20]


In [49]:
#Menghitung Akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar : 17 data
Prediksi Salah : 3 data
Akurasi : 85.0 %
